export const FAKE_PROFESSIONALS = [
    {
        id: 1,
        nome: "Dr. Ricardo Oliveira",
        documento: "CRO-SP 12345",
        especialidade: "Implantodontia",
        ativo: true,
        empresaId: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        isDeleted: false,
    },
    {
        id: 2,
        nome: "Dra. Juliana Mendes",
        documento: "CRO-RJ 88765",
        especialidade: "Ortodontia",
        ativo: true,
        empresaId: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        isDeleted: false,
    },
    {
        id: 3,
        nome: "Dr. Carlos Alberto",
        documento: "CRO-MG 44321",
        especialidade: "Endodontia",
        ativo: false,
        empresaId: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        isDeleted: false,
    },
    {
        id: 4,
        nome: "Dra. Beatriz Santos",
        documento: "CRO-SC 99001",
        especialidade: "Odontopediatria",
        ativo: true,
        empresaId: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        isDeleted: false,
    },
    {
        id: 5,
        nome: "Dr. Henrique Farias",
        documento: "CRO-PR 55667",
        especialidade: "Clínico Geral",
        ativo: true,
        empresaId: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        isDeleted: false,
    }
];
